spring:
  banner:
    location: classpath:banner/banner.txt
    image:
     location: classpath:fotocreador/microservicios.png
#  config:
    import: optional:configserver:http://localhost:7000
  cloud:
    config:
      profile: dev
  
     
     
  